### get all persons
GET http://localhost:3001/api/persons

### get info
GET http://localhost:3001/info

### single entry
GET http://localhost:3001/api/persons/4

### delete
DELETE http://localhost:3001/api/persons/4